[package]
name = "hringas"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "no libc, no_std, pure rust bindings to io_uring"

[dependencies]
rustix = { version = "1.1.2", features = ["io_uring", "mm"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
